---
title: Class Schedule Example
subtitle: Your class, Fall 2025
author: Your Name
date: last-modified
format: class-schedule-pdf
color: 5555ff         # Main color theme
color-odd: cbcdf8     # Odd rows in the table
color-even: EEEEEE    # Even rows in the table
color-heading: 5555ff # Background color of the section heading numbers, if formatted
heading-format: true
logo: logo.png
logo-placement: L
logo-height: 40pt
logo-text: | 
    University of XXX 

    Department of YYY

---


## Introduction


You can use the `class-schedule-pdf` quarto extension to create a PDF document that renders a specially formatted list of topics, along a pre-defined span of days, allowing you to select the recurring days of the week for the topics. This is particularly useful for creating a syllabus or a class schedule document. The classes are rendered in a table, laying out the topics along with their respective dates and additional descriptions that can be added to the topics.

To render use: 

* `quarto render template.qmd`
* `quarto render template.qmd --to class-schedule-pdf` change `class-schedule-pdf` to `class-schedule-html` or `class-schedule-docx` for other formats (html, docx, odt, markdown).

## Rendered schedule

::: {.schedule 
start="29/04/2025" 
end="28/06/2025" 
days="1,3,5" 
headers="Class,Day,Section,Description" 
dateformat="%a - %b, %d %Y"}

# Introduction 

Regular text of the description.

# Introduction (cont.)

Any text can be added here, including lists:

- Welcome
- Course Overview


# Sub-header

You can also have sub-headers in the table, which will be rendered as a separate row in the table. Add `##` for a sub-header. The class `{.unnumbered}` is important to avoid mixing up the numbering with regular level 2 headers.

## Theory {.unnumbered}

- Topic 1
- Topic 2

## Practice {.unnumbered}

- Exercises

# Another class 

Another formatting is the [definition list](https://quarto.org/docs/authoring/markdown-basics.html#lists) notation below. The two spaces after the colon (:) are important to render the definition list correctly.: 

Practice exercises
:  

(@) Exercises 1
(@) Exercises 2
(@) Exercises 3

* Computer lab
   1. Exercises 1

# Class XXX

This is a class with a very long description that will be wrapped in the table cell. It should be long enough to demonstrate how the text wraps around in the table cell. This is useful for showing how the schedule can accommodate longer descriptions without breaking the layout.

:::